jobs:
  build:
    steps:
      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # 确保名称一致
          password: ${{ secrets.DOCKER_PASSWORD }}  # 确保名称一致
