jobs:
  build:
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4

      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/wxchat
          tags: |
            type=raw,value=latest
      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Debug Secrets
          run: |
            echo "DOCKER_USERNAME: $DOCKER_USERNAME"
            echo "DOCKER_PASSWORD: $DOCKER_PASSWORD"

      - 
        name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # 确保名称一致
          password: ${{ secrets.DOCKER_PASSWORD }}  # 确保名称一致
